In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(1.0)
b = tf.constant(2.0)

c = a*b
print a
print b
print c

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("mul:0", shape=(), dtype=float32)


In [3]:
sess = tf.Session()
c_value = sess.run(c)
print c_value

2.0


In [4]:
a = tf.placeholder(shape=[3], dtype=tf.float32)
b = tf.Variable(tf.ones([3]))

c = a+b
print a
print b
print c

Tensor("Placeholder:0", shape=(3,), dtype=float32)
<tf.Variable 'Variable:0' shape=(3,) dtype=float32_ref>
Tensor("add:0", shape=(3,), dtype=float32)


In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
b_value = sess.run(b)
c_value = sess.run(c,{a:[1.0,2.0,3.0]})
print b_value
print c_value

[ 1.  1.  1.]
[ 2.  3.  4.]


In [6]:
with tf.variable_scope('my_scope'):
    b = tf.Variable(tf.ones([3]), name='b')
    
print b

<tf.Variable 'my_scope/b:0' shape=(3,) dtype=float32_ref>


In [7]:
c = tf.get_variable('my_scope/c',shape=[3],
                    initializer=tf.ones_initializer())
    
print c

<tf.Variable 'my_scope/c:0' shape=(3,) dtype=float32_ref>


In [8]:
with tf.variable_scope('my_scope',reuse=True):
    d = tf.get_variable('c')
    
print d

<tf.Variable 'my_scope/c:0' shape=(3,) dtype=float32_ref>


In [9]:
x = tf.placeholder(shape=[3],dtype=tf.float32)
y = tf.placeholder(shape=[3],dtype=tf.float32)
weights = tf.get_variable('w',shape=[3],initializer=tf.ones_initializer)

MSE = tf.reduce_mean(tf.square(weights*x-y))

In [10]:
learning_rate = 0.1
momentum = 0.9
opt = tf.train.MomentumOptimizer(learning_rate,momentum)
train = opt.minimize(MSE)

In [11]:
x_feed = [1,-1,2]
y_feed = [2,3,4]
sess.run(tf.global_variables_initializer())
for i in range(100):
    sess.run(train,{x:x_feed,y:y_feed})
    
print sess.run(weights)

[ 1.9966023  -2.98640919  2.00517011]


In [12]:
input_size = 100
output_size = 10
init = tf.random_normal_initializer(mean=0.0,stddev=1e-2)

x = tf.placeholder(shape=[1,input_size],dtype=tf.float32)
y = tf.placeholder(shape=[1,output_size],dtype=tf.float32)

with tf.variable_scope('layer_1'):
    W = tf.get_variable('W',[input_size,output_size],
                        initializer=init)
    b = tf.get_variable('b',[output_size],
                        initializer=init)
    
    h = tf.matmul(x,W)+b
    a = tf.nn.sigmoid(h)
    
MSE = tf.reduce_mean(tf.square(a-y))